### ISSUE TITLE
Sun Safety Failure

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/scheduler#158]
Found a sun safety error related to planning planet scans. 

On master branch with this config file 
```
platform: satp2

# yaml loads iso format automatically into datetimes
t0: 2025-01-13T17:00:00+00:00
t1: 2025-01-14T17:00:00+00:00
t0_state_file: satp2/state_files/state_2025-01-13T17:00:00+00:00.npy

elevation: 60
min_hwp_el: 48

apply_boresight_rotation: True 
#hwp_override: False # True: forwards, False: backwards
home_at_end: False # Home: spin down HWP
run_relock: False # Relock detectors at the beginning of the schedule
iv_cadence: 10800 ## take IVs every three hours
#bias_step_cadence: 900 ## min bias step cadence 

cal_targets:
  - source: saturn
    # boresight: # if not specified, use scan boresight
    elevation: 50
    boresight: 45
    focus: 'ws3'
    allow_partial: False
    az_speed: 0.8
    az_accel: 1.0
```

this hits a sun safety error here: 
```
run.acu.move_to(az=111.5, el=60.0)
run.wait_until('2025-01-13T21:34:27.265072+00:00')
# hwp already spinning with forward=False
run.smurf.bias_step(concurrent=True)
run.wait_until('2025-01-13T21:46:27.295072+00:00')
run.seq.scan(
    description='SOUTHERN FIELD (SE)',
    stop_time='2025-01-13T22:21:54.530143+00:00',
    width=40.0, az_drift=0,
    subtype='cmb', tag='db16613e-68bf-49c2-9116-b588eaba4468,112-152',
    min_duration=600,
)

#run.acu.move_to(az=111.5, el=70.0)  <-----moves I added to make this sun safe
#run.acu.move_to(az=296.168, el=70.0)
run.acu.move_to(az=296.168, el=50.0)
run.wait_until('2025-01-13T22:21:54.530143+00:00')

################### Detector Setup######################
```
