### ISSUE TITLE
LAT Calibration vs CMB Scans

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/scheduler#190]
This is a strange thing I don't think I've seen before. When I run the below config with `no_cmb=True` then I get all three planet scans. But, if I run with `no_cmb=False` then we get a CMB scan instead of one of the planets. 

```
platform: lat

# yaml loads iso format automatically into datetimes
t0: 2025-03-01T00:00:00+00:00
t1: 2025-03-01T11:00:00+00:00
t0_state_file: None

elevation: 40
corotator: 0

az_speed: 1 ## will get set to 1/cos(el)
az_accel: 4
elevations_under_90: True
no_cmb: True
home_at_end: True

remove_targets:
  - Uranus 
  - Jupiter
  - Venus
  - Mars
  - TauA
  - GalacticCenter

cal_targets: 
  - source: 'jupiter'
    elevation: 35
    focus: i3_ws1,i3_ws2,i4_ws1,i4_ws2
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0 
  - source: 'mars'
    elevation: 35
    focus: i3_ws1,i3_ws2,i4_ws1,i4_ws2
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0 
  - source: 'mars'
    elevation: 40
    focus: i6_ws1,i6_ws2,i1_ws1,i1_ws2
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0 
```
