### ISSUE TITLE
Sun safety issues from moving too early for detector setup?

### ISSUE THREAD

**Issue by kmharrington** [simonsobs/scheduler#196]
This has come up in the past but I'm seeing it again so reposting! (and this time I'm actually working on the main branch)

running with this config:
```
platform: satp2

t0: 2025-03-08T17:00:00+00:00
t1: 2025-03-09T17:00:00+00:00

elevation: 60
min_hwp_el: 48.0

az_speed: 0.1
az_accel: 0.1
az_motion_override: True

apply_boresight_rotation: True 
home_at_end: False # Home: spin down HWP
relock_cadence: 86400 # Relock every 24 hours
iv_cadence: 10800 ## take IVs every three hours


#t0_state_file: satp2/state_files/state_2025-02-14T17:00:00+00:00.npy
t0_state_file: None


cal_targets: 
  - source: jupiter
    boresight: -45
    elevation: 48
    focus: 'ws0,ws6'
    allow_partial: True
    az_speed: 0.8
    az_accel: 1.0
  - source: jupiter
    boresight: -45
    elevation: 48
    focus: 'ws0,ws6'
    allow_partial: True
    az_speed: 0.8
    az_accel: 1.0
```

I get an output where 
```
################## Relock Over #######################

run.wait_until('2025-03-08T17:15:01.030000+00:00')
run.acu.move_to(az=180, el=48.0)
run.wait_until('2025-03-08T17:28:11.030000+00:00')
run.acu.move_to(az=111.5, el=60.0)                 <<<-------------------------this line is not Sun Safe
run.wait_until('2025-03-08T17:28:11.030000+00:00')
run.acu.set_boresight(-45)

################### Detector Setup######################
with disable_trace():
    run.initialize()
run.smurf.take_bgmap(concurrent=True)
run.smurf.take_noise(concurrent=True, tag='res_check')
run.smurf.iv_curve(concurrent=True, 
    iv_kwargs={'run_serially': False, 'cool_wait': 60*5})
run.smurf.bias_dets(concurrent=True)
time.sleep(180)
run.smurf.bias_step(concurrent=True)
run.smurf.take_noise(concurrent=True, tag='bias_check')
#################### Detector Setup Over ####################

sup.enable_driver_board()
run.hwp.set_freq(freq=-2)
run.wait_until('2025-03-08T17:56:11.050000+00:00')
run.seq.scan(
    description='SOUTHERN FIELD (SE)',
    stop_time='2025-03-08T18:15:59.950000+00:00',
```
