### ISSUE TITLE
Schedule "not sunsafe" - when the sun is at -24 degrees elevations

### ISSUE THREAD

**Issue by sdicker** [simonsobs/scheduler#206]
Maybe we should not fix this as the LAT might throw a fault - others will know better, but the following schedule was declared not sun safe.  If we don't fix it then it would be nice to skip the problem scan.  For some reason similar scripts have been working on other nights - I suspect as they switch to the other CMB field slightly earlier.  Note like all shared LAT files, the yaml files live in a nice shared area : /so/scratch/LAT_files/.

```
platform: lat

# yaml loads iso format automatically into datetimes
t0: 2025-03-24T21:45:00+00:00
t1: 2025-03-25T11:00:00+00:00
t0_state_file: None

elevation: 40
corotator: 0

az_speed: 1 ## will get set to 1/cos(el)
az_accel: 4
elevations_under_90: True
no_cmb: False
home_at_end: True

remove_targets:
  - Uranus 
  - Jupiter
  - Venus
  - Mars
  - TauA
  - GalacticCenter

#script to try and get CMB map with lots of pointing scans on same set of arrays at same elevation (40 degrees)
cal_targets: 
  - source: 'mars'
    elevation: 40
    focus: i3_ws0,i4_ws0
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0
  - source: 'mars'
    elevation: 30
    focus: i3_ws0,i4_ws0
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0
  - source: 'mars'
    elevation: 35
    focus: i3_ws0,i4_ws0
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0
      #- source: 'jupiter'
      #   elevation: 35
      # focus: i3_ws1,i3_ws2,i4_ws1,i4_ws2
      # allow_partial: True
      #az_speed: 0.5
      #az_accel: 1.0 
  - source: 'jupiter'
    elevation: 40
    focus: i3_ws0,i4_ws0
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0 
  - source: 'jupiter'
    elevation: 40
    focus: i3_ws0,i4_ws0
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0
      #  - source: 'jupiter'
      #    elevation: 40
      #    focus: c1_ws0,i5_ws0
      #    allow_partial: True
      #    az_speed: 0.5
      #    az_accel: 1.0
  - source: 'uranus'
    elevation: 40
    focus: i3_ws0,i4_ws0
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0
  - source: 'uranus'
    elevation: 25
    focus: i3_ws0,i4_ws0
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0
      #  - source: 'uranus'
      #    elevation: 40
      #    focus: c1_ws1,c1_ws2,i5_ws1,i5_ws2
      #    allow_partial: True
      #    az_speed: 0.5
      #    az_accel: 1.0
  - source: 'j2134n0152' #Source for Adam 
    focus: i3_ws0,i4_ws0
    elevation: 15
    ra: 323.543
    dec: -1.888
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0 
  - source: 'j1058p0133' #5Jy in band 3 Alma gridcal 
    focus: i3_ws0,i4_ws0
    elevation: 30
    ra: 164.623
    dec: 1.5663
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0
  - source: 'j1058p0133' #5Jy in band 3 Alma gridcal
    focus: i3_ws0,i4_ws0
    elevation: 60
    ra: 164.623
    dec: 1.5663
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0
      # maybe 130Jy - not compact 
  - source: 'rcw38'
    elevation: 60 #40 degrees seems to crash the scheduler
    focus: i3_ws0,i4_ws0
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0 
  - source: 'rcw38'
    elevation: 50
    focus: i3_ws0,i4_ws0
    allow_partial: True
    az_speed: 0.5
    az_accel: 1.0`
```
``
```
