### ISSUE TITLE
Wait command times are sometimes reversed

### ISSUE THREAD

**Issue by mmccrackan** [simonsobs/scheduler#241]
Not really a problem but just a note to self to check why the `wait_until` end time goes back in time:

```
run.acu.move_to(az=180.0, el=99.0)
run.wait_until('2025-05-11T17:08:03+00:00')
run.acu.move_to(az=30.0, el=40.0)
run.wait_until('2025-05-11T16:57:43+00:00')
```

Happens on this config:

```
platform: lat

# yaml loads iso format automatically into datetimes
t0: 2025-05-10T19:00:00+00:00
t1: 2025-05-11T19:00:00+00:00
t0_state_file: None

elevation: 40
corotator: 0 

az_speed: 1 ## will get set to 1/cos(el)
az_accel: 4
elevations_under_90: True
no_cmb: False
#home_at_end: True
open_shutter: True
close_shutter: True

az_offset: 0.0
el_offset: 0.0  #combined eta el

remove_targets:
  - Uranus 
  #  - Jupiter
  - Venus
  - Mars
  - Neptune
    #  - TauA
    #  - GalacticCenter

#script to try and get CMB map with lots of pointing scans on same set of arrays at same elevation (40 degrees)
cal_targets: 
  - source: 'mars'
    elevation: 40.
    focus: c1_ws1,c1_ws2,c1_ws0,i5_ws0,i5_ws1,i5_ws2 #i3_ws1,i3_ws2,i3_ws0,i4_ws0,i4_ws1,i4_ws2 #i6_ws1,i6_ws2,i6_ws0,i1_ws0,i1_ws1,i1_ws2
    allow_partial: False
    az_speed: 0.5
    az_accel: 1.0
    corotator: 0 
  - source: 'mars'
    elevation: 140.
    focus: c1_ws1,c1_ws2,c1_ws0,i5_ws0,i5_ws1,i5_ws2 #i3_ws1,i3_ws2,i3_ws0,i4_ws0,i4_ws1,i4_ws2 #i6_ws1,i6_ws2,i6_ws0,i1_ws0,i1_ws1,i1_ws2
    allow_partial: False
    az_speed: 0.5
    az_accel: 1.0
    corotator: 0
  - source: 'neptune'
    elevation: 65.
    focus: i6_ws1,i6_ws2,i6_ws0,i1_ws0,i1_ws1,i1_ws2 #c1_ws1,c1_ws2,c1_ws0,i5_ws0,i5_ws1,i5_ws2 #i3_ws1,i3_ws2,i3_ws0,i4_ws0,i4_ws1,i4_ws2
    allow_partial: False
    az_speed: 0.5
    az_accel: 1.0
    corotator: 0
  - source: 'neptune'
    elevation: 115.
    focus: i6_ws1,i6_ws2,i6_ws0,i1_ws0,i1_ws1,i1_ws2 #c1_ws1,c1_ws2,c1_ws0,i5_ws0,i5_ws1,i5_ws2 #i3_ws1,i3_ws2,i3_ws0,i4_ws0,i4_ws1,i4_ws2
    allow_partial: False
    az_speed: 0.5
    az_accel: 1.0
    corotator: 0
      #saturn and neptune are about at the same location on 7/5/2025
  - source: 'saturn'
    elevation: 67.
    focus: i3_ws1,i3_ws2,i3_ws0,i4_ws0,i4_ws1,i4_ws2 #i6_ws1,i6_ws2,i6_ws0,i1_ws0,i1_ws1,i1_ws2
    allow_partial: False
    az_speed: 0.5
    az_accel: 1.0
    corotator: 0
  - source: 'saturn'
    elevation: 140.
    focus: i3_ws1,i3_ws2,i3_ws0,i4_ws0,i4_ws1,i4_ws2 #i6_ws1,i6_ws2,i6_ws0,i1_ws0,i1_ws1,i1_ws2
    allow_partial: False
    az_speed: 0.5
    az_accel: 1.0
    corotator: 0
  - source: 'uranus'
    elevation: 45.
    focus: c1_ws1,c1_ws2,c1_ws0,i5_ws0,i5_ws1,i5_ws2
    allow_partial: False
    az_speed: 0.5
    az_accel: 1.0
    corotator: 0
  - source: 'uranus'
    elevation: 135.
    focus: c1_ws1,c1_ws2,c1_ws0,i5_ws0,i5_ws1,i5_ws2
    allow_partial: False
    az_speed: 0.5
    az_accel: 1.0
    corotator: 0

      #  - source: 'j1256n0547' #8.35Jy in ALMA band 3
      #    focus: i3_ws0,i3_ws1,i3_ws2,i4_ws0,i4_ws1,i4_ws2 
      #    elevation: 70
      #    ra: 194.047
      #    dec: -5.789
      #    allow_partial: False
      #    az_speed: 0.5
      #    az_accel: 1.0
      #    corotator: -25
      #  - source: 'rcw38'
      #    elevation: 60 #40 degrees seems to crash the scheduler
      #    focus: i6_ws1,i6_ws2,i6_ws0,i1_ws0,i1_ws1,i1_ws2
      #    allow_partial: False
      #    az_speed: 0.5
      #    az_accel: 1.0
      #    corotator: -25
      #  - source: 'venus'
      #    elevation: 30
      #    focus: c1_ws1,c1_ws2,i5_ws1,i5_ws2
      #    allow_partial: False
      #    az_speed: 0.5
      #    az_accel: 1.0
      #    corotator: -25
      #  - source: 'j2134n0152' #Source for Adam 
      # focus: c1_ws1,c1_ws2,i5_ws1,i5_ws2
      # elevation: 20
      # ra: 323.543
      # dec: -1.888
      # allow_partial: False
      #  az_speed: 0.5
      #  Said to be 130Jy
      #  - source: '(r13p416dn43p01)cena'
      #    elevation: 40
      #    ra: 13.416
      #    dec: -43.01
      #    focus: all
      #    allow_partial: False
      #  - source: 'tcrb' #exploding star
      #  elevation: 30
      #  focus: all
      #  allow_partial: False
      #  az_speed: 0.5
      #  az_accel: 1.0
      #  ra: 239.876
      #  dec: 25.920
#  ### source 3
#  - source: '(r-81.5836d-21.0609)'
#    ra: -81.5836
#    dec: -21.0609
#    focus: i1_ws0,i1_ws1,i1_ws2,i6_ws0,i6_ws1,i6_ws2
#    allow_partial: True
#  ### galcenter point
#  - source: '(r-93.17d-28.38),sgrb2'
#    ra: -93.17
#    dec: -28.38
#    focus: i3_ws0,i3_ws1,i3_ws2,i4_ws0,i4_ws1,i4_ws2
#    allow_partial: True
#  ### galcenter point
#  - source: '(r-93.17d-28.38),sgrb2'
#    ra: -93.17
#    dec: -28.38
#    focus: c1_ws0,c1_ws1,c1_ws2,i5_ws0,i5_ws1,i5_ws2
#    allow_partial: True
#  - source: 'moon'
#    focus: all
#    allow_partial: True
```
